[package]
name = "liquid-research-classic"
version = "0.9.0"
edition = "2021"

[dependencies]
liquid-protocol = { path = "../liquid-protocol" }
liquid-research-artifacts = { path = "../liquid-research-artifacts" }
liquid-research-core = { path = "../liquid-research-core" }
serde_json = { workspace = true }
url = { workspace = true }
